server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"

adapters:
  r2dbc:
   url: r2dbc:postgresql://localhost:5432/BD Autenticacion
   username: postgres
   password: admin
   host: localhost
   port: 5432
   database: BD Autenticacion
   schema: public
